version: '2'
services:
    greatwalks-app:
        image: greatwalks
        external_links:
            - greatwalks-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/GreatWalks
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    greatwalks-postgresql:
        extends:
            file: postgresql.yml
            service: greatwalks-postgresql
